---
title: '170207'
output: pdf_document
---
#RL Data  
  
```{r, echo = FALSE, warning=FALSE}
library(platetools)
library(ggplot2)
library(viridis)
library(plyr)
library(reshape2)
library(pipeR)

#####1-18-17#####
#import data
df <- read.csv("170207_plateEffects.csv") %>>% subset(select = c(PlateNum, CloneKey, Odor1K, Odor1C, PlateLocation, RLData, LucData, Notes))

#graph RL of all plates
for (i in 1:6){
  RL.data <- subset(df, PlateNum == i)
  plotRL <- raw_map(data = RL.data$RLData, 
          well = RL.data$PlateLocation,
          plate = 384) +
    scale_fill_viridis()+
    theme_dark() +
    ggtitle(paste("plate ", i))
  print(plotRL)
  
}
RL.data.5a <- subset(df, PlateNum == 6)
raw_map(data = RL.data.5a$LucData, 
        well = RL.data.5a$PlateLocation,
        plate = 384) +
  scale_fill_viridis()+
  theme_dark() +
  ggtitle("plate 5 second run through")
```
  
#Luc Data  
  
```{r, echo = FALSE}
#graph luc data
for (i in 1:5){
  RL.data <- subset(df, PlateNum == i)
  plotRL <- raw_map(data = RL.data$LucData, 
                    well = RL.data$PlateLocation,
                    plate = 384) +
    scale_fill_viridis()+
    theme_dark() +
    ggtitle(paste("plate ", i))
  print(plotRL)
  
}
```
  
#Model the plate effects by row and calculate the percent of variation explained by the model.  
Remember that both runs on "plate 6"" are actually RL data from the rerun of plate 5.  
  
  
```{r, echo = FALSE}
df$row <- df$PlateLocation
for (i in c(10, 20,1:9,11:19,21:24)){
  df$row<-gsub(paste0(i),"",df$row)
}
df$rowNum <- rep(1:16, 24)#make the rows into numbers for the linear model
#model all of them
for (i in 1:6){
  #model plate 1 RL
  RL.data <- subset(df, PlateNum == i)
  df.model.RL <- lm(RLData~rowNum, data = RL.data) #define the linear model
  df.eqrl = function(x){summary(df.model.RL)$coefficients[2,1]*x + (summary(df.model.RL)$coefficients[1,1])}
  #put data in df
  #   p.r.data[i+1,4] <- summary(df.model.RL)$r.squared
  #   p.r.data[i+1,3] <- summary(df.model.RL)$coefficients[2,4]
  df.model <- lm(LucData~rowNum, data = RL.data) #define the linear model
  df.eqluc = function(x){summary(df.model)$coefficients[2,1]*x + (summary(df.model)$coefficients[1,1])}
  #   p.r.data[i+1,6] <- summary(df.model)$r.squared
  #   p.r.data[i+1,5] <- summary(df.model)$coefficients[2,4]
  #plot it
  RL.data.melt <- melt(RL.data, c("PlateLocation", "PlateNum", "row", "rowNum", "CloneKey", "Odor1K", "Odor1C", "Notes")) 
  #graph!
  print(
    ggplot(data = subset(RL.data.melt, variable %in% c("RLData", "LucData")) , aes(x = row, y = value, colour = variable)) +
      geom_point() +
      geom_smooth(method = lm) +
      stat_function(fun = df.eqrl, colour = "#F8766D") +
      annotate("text", x=4, y = max(RL.data$LucData), label = paste("p=",summary(df.model.RL)$coefficients[2,4]), colour = "#F8766D")+
      annotate("text", x=12, y = max(RL.data$LucData), label = paste("R^2=",summary(df.model.RL)$r.squared), colour = "#F8766D")+
      stat_function(fun = df.eqluc, colour = "#00BFC4") +
      annotate("text", x=4, y = max(RL.data$LucData) + 400, label = paste("p=",summary(df.model)$coefficients[2,4]), colour = "#00BFC4")+
      annotate("text", x=12, y = max(RL.data$LucData) + 400, label = paste("R^2=",summary(df.model)$r.squared), colour = "#00BFC4")+
      ggtitle(paste("plate", i))
  )
}

```